# Generated by Django 5.2.4 on 2025-07-21 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='simple_user', max_length=32)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('faculty', models.CharField(choices=[('فیزیک', 'فیزیک'), ('صنایع', 'صنایع'), ('کامپیوتر', 'کامپیوتر'), ('برق', 'برق'), ('عمران', 'عمران'), ('مواد', 'مواد'), ('مهندسی شیمی و نفت', 'مهندسی شیمی و نفت'), ('ریاضی', 'ریاضی'), ('هوافضا', 'هوافضا'), ('انرژی', 'انرژی'), ('مدیریت و اقتصاد', 'مدیریت و اقتصاد'), ('شیمی', 'شیمی'), ('مکانیک', 'مکانیک')], default='نامشخص', max_length=64)),
                ('dormitory', models.CharField(blank=True, choices=[('احمدی روشن', 'احمدی روشن'), ('طرشت ۲', 'طرشت ۲'), ('طرشت ۳', 'طرشت ۳'), ('خوابگاهی نیستم', 'خوابگاهی نیستم')], default='خوابگاهی نیستم', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوای اصلی')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('tags', models.TextField(blank=True, verbose_name='برچسب\u200cها')),
                ('category', models.CharField(choices=[('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('گزارش\u200cها', 'گزارش\u200cها'), ('اطلاعیه\u200cها', 'اطلاعیه\u200cها'), ('داستان\u200cهای دانشجویی', 'داستان\u200cهای دانشجویی'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='دسته\u200cبندی')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='آدرس تصویر')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('reading_time', models.IntegerField(default=0, verbose_name='زمان مطالعه (دقیقه)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مطلب بلاگ',
                'verbose_name_plural': 'مطالب بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('tags', models.TextField(blank=True, verbose_name='برچسب\u200cها')),
                ('category', models.CharField(choices=[('مسائل دانشگاهی', 'مسائل دانشگاهی'), ('فیزیک', 'فیزیک'), ('صنایع', 'صنایع'), ('کامپیوتر', 'کامپیوتر'), ('برق', 'برق'), ('عمران', 'عمران'), ('مواد', 'مواد'), ('مهندسی شیمی و نفت', 'مهندسی شیمی و نفت'), ('ریاضی', 'ریاضی'), ('هوافضا', 'هوافضا'), ('انرژی', 'انرژی'), ('مدیریت و اقتصاد', 'مدیریت و اقتصاد'), ('شیمی', 'شیمی'), ('مکانیک', 'مکانیک'), ('احمدی روشن', 'احمدی روشن'), ('طرشت ۲', 'طرشت ۲'), ('طرشت ۳', 'طرشت ۳'), ('خوابگاهی نیستم', 'خوابگاهی نیستم')], default='مسائل دانشگاهی', max_length=64, verbose_name='دسته\u200cبندی')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='آدرس تصویر')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('deadline', models.DateTimeField(verbose_name='ددلاین')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('closed', 'بسته شده')], default='pending', max_length=16, verbose_name='وضعیت')),
                ('anonymous_allowed', models.BooleanField(default=True, verbose_name='امضای ناشناس مجاز است؟')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'کارزار',
                'verbose_name_plural': 'کارزارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.CharField(default='public', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaignsignatures', to='api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
