# Generated by Django 5.2.4 on 2025-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dormitory',
            field=models.CharField(blank=True, choices=[('احمدی روشن', 'احمدی روشن'), ('طرشت ۲', 'طرشت ۲'), ('طرشت ۳', 'طرشت ۳'), ('خوابگاهی نیستم', 'خوابگاهی نیستم')], default='خوابگاهی نیستم', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(choices=[('فیزیک', 'فیزیک'), ('صنایع', 'صنایع'), ('کامپیوتر', 'کامپیوتر'), ('برق', 'برق'), ('عمران', 'عمران'), ('مواد', 'مواد'), ('مهندسی شیمی و نفت', 'مهندسی شیمی و نفت'), ('ریاضی', 'ریاضی'), ('هوافضا', 'هوافضا'), ('انرژی', 'انرژی'), ('مدیریت و اقتصاد', 'مدیریت و اقتصاد'), ('شیمی', 'شیمی'), ('مکانیک', 'مکانیک')], default='نامشخص', max_length=64),
        ),
    ]
