# Generated by Django 5.2.4 on 2025-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='max_choices',
            field=models.IntegerField(blank=True, help_text='حداکثر تعداد انتخاب مجاز برای رأی\u200cدهنده (در حالت چندگزینه\u200cای). اگر خالی باشد، نامحدود است.', null=True),
        ),
    ]
