# Generated by Django 5.2.4 on 2025-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_dormitory_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcampaign',
            name='label',
            field=models.CharField(choices=[('مسائل دانشگاهی', 'مسائل دانشگاهی'), ('فیزیک', 'فیزیک'), ('صنایع', 'صنایع'), ('کامپیوتر', 'کامپیوتر'), ('برق', 'برق'), ('عمران', 'عمران'), ('مواد', 'مواد'), ('مهندسی شیمی و نفت', 'مهندسی شیمی و نفت'), ('ریاضی', 'ریاضی'), ('هوافضا', 'هوافضا'), ('انرژی', 'انرژی'), ('مدیریت و اقتصاد', 'مدیریت و اقتصاد'), ('شیمی', 'شیمی'), ('مکانیک', 'مکانیک'), ('احمدی روشن', 'احمدی روشن'), ('طرشت ۲', 'طرشت ۲'), ('طرشت ۳', 'طرشت ۳'), ('خوابگاهی نیستم', 'خوابگاهی نیستم')], default='مسائل دانشگاهی', max_length=64),
        ),
    ]
