# Generated by Django 5.2.4 on 2025-07-19 00:51

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.pendingcampaign'),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='is_anonymous',
            field=models.CharField(choices=[('public', 'Public'), ('anonymous', 'Anonymous')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='user_email',
            field=models.EmailField(max_length=254, validators=[api.models.validate_sharif_email]),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters long'), api.models.validate_no_special_chars]),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[api.models.validate_sharif_email]),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='is_anonymous',
            field=models.CharField(choices=[('public', 'Public'), ('anonymous', 'Anonymous')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters long'), api.models.validate_no_special_chars]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[api.models.validate_sharif_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('simple_user', 'Simple User'), ('head', 'Head'), ('center_member', 'Center Member'), ('superadmin', 'Super Admin')], default='simple_user', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='campaignsignature',
            unique_together={('campaign', 'user')},
        ),
        migrations.AddIndex(
            model_name='campaignsignature',
            index=models.Index(fields=['campaign', 'user'], name='api_campaig_campaig_05b055_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsignature',
            index=models.Index(fields=['signed_at'], name='api_campaig_signed__350d8a_idx'),
        ),
    ]
