# Generated by Django 5.2.4 on 2025-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_poll_is_public_poll_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_council_member',
            field=models.BooleanField(default=False, verbose_name='عضو شورای عمومی'),
        ),
    ]
