# Generated by Django 5.2.4 on 2025-07-19 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_verificationcode_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignsignature',
            name='api_campaig_campaig_05b055_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaignsignature',
            name='api_campaig_signed__350d8a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campaignsignature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pendingcampaign'),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='is_anonymous',
            field=models.CharField(default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignsignature',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='is_anonymous',
            field=models.CharField(default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='simple_user', max_length=32),
        ),
    ]
