# Generated by Django 5.2.4 on 2025-07-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_council_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_council_member',
        ),
        migrations.AddField(
            model_name='user',
            name='council_member_status',
            field=models.CharField(choices=[('member', 'عضو'), ('observer', 'عضو بدون حق رای'), ('none', 'غیرعضو')], default='none', max_length=16, verbose_name='عضویت شورای عمومی'),
        ),
    ]
