# Generated by Django 5.2.4 on 2025-07-20 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_campaignsignature_api_campaig_campaig_05b055_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='شناسه URL')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('tags', models.JSONField(default=list, verbose_name='برچسب\u200cها')),
                ('category', models.CharField(default='عمومی', max_length=100, verbose_name='دسته\u200cبندی')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('reading_time', models.IntegerField(default=5, verbose_name='زمان خواندن (دقیقه)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
