# Generated by Django 5.2.4 on 2025-07-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'مطلب بلاگ', 'verbose_name_plural': 'مطالب بلاگ'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تصویر'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
