# Generated by Django 5.2.4 on 2025-07-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_poll_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user_email',
        ),
        migrations.CreateModel(
            name='PollParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'poll')},
            },
        ),
    ]
