# Generated by Django 5.2.4 on 2025-07-23 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pollvote_unique_together_remove_pollvote_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='رأی\u200cدهنده'),
        ),
    ]
