# Generated by Django 5.2.4 on 2025-07-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blogpost_options_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('آموزش', 'آموزش'), ('گزارش', 'گزارش'), ('مصاحبه', 'مصاحبه'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='برچسب\u200cها'),
        ),
    ]
