# Generated by Django 5.2.4 on 2025-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blogpost_category_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('گزارش', 'گزارش'), ('اطلاعیه', 'اطلاعیه'), ('مصاحبه', 'مصاحبه'), ('سایر', 'سایر')], default='اخبار', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.TextField(blank=True, verbose_name='برچسب\u200cها'),
        ),
    ]
