# Generated by Django 5.2.4 on 2025-07-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_blogpost_category_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('گزارش\u200cها', 'گزارش\u200cها'), ('اطلاعیه\u200cها', 'اطلاعیه\u200cها'), ('داستان\u200cهای دانشجویی', 'داستان\u200cهای دانشجویی'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=0, verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='نامک'),
        ),
    ]
