# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='متن کامل'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='توضیحات'),
        ),
    ]
